# Generated by Django 2.2.17 on 2021-01-25 13:59

from django.db import migrations, models
import photo.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', stdimage.models.StdImageField(default='profile.png', null=True, upload_to=photo.models.get_file_path, verbose_name='Imagem')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Descrição')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
